// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/realworld/v1/realworld.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTagsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagsRequest) Reset()         { *m = GetTagsRequest{} }
func (m *GetTagsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTagsRequest) ProtoMessage()    {}
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{0}
}

func (m *GetTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagsRequest.Unmarshal(m, b)
}
func (m *GetTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagsRequest.Marshal(b, m, deterministic)
}
func (m *GetTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagsRequest.Merge(m, src)
}
func (m *GetTagsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTagsRequest.Size(m)
}
func (m *GetTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagsRequest proto.InternalMessageInfo

type FavoriteArticleRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteArticleRequest) Reset()         { *m = FavoriteArticleRequest{} }
func (m *FavoriteArticleRequest) String() string { return proto.CompactTextString(m) }
func (*FavoriteArticleRequest) ProtoMessage()    {}
func (*FavoriteArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{1}
}

func (m *FavoriteArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteArticleRequest.Unmarshal(m, b)
}
func (m *FavoriteArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteArticleRequest.Marshal(b, m, deterministic)
}
func (m *FavoriteArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteArticleRequest.Merge(m, src)
}
func (m *FavoriteArticleRequest) XXX_Size() int {
	return xxx_messageInfo_FavoriteArticleRequest.Size(m)
}
func (m *FavoriteArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteArticleRequest proto.InternalMessageInfo

func (m *FavoriteArticleRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type UnfavoriteArticleRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfavoriteArticleRequest) Reset()         { *m = UnfavoriteArticleRequest{} }
func (m *UnfavoriteArticleRequest) String() string { return proto.CompactTextString(m) }
func (*UnfavoriteArticleRequest) ProtoMessage()    {}
func (*UnfavoriteArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{2}
}

func (m *UnfavoriteArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfavoriteArticleRequest.Unmarshal(m, b)
}
func (m *UnfavoriteArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfavoriteArticleRequest.Marshal(b, m, deterministic)
}
func (m *UnfavoriteArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfavoriteArticleRequest.Merge(m, src)
}
func (m *UnfavoriteArticleRequest) XXX_Size() int {
	return xxx_messageInfo_UnfavoriteArticleRequest.Size(m)
}
func (m *UnfavoriteArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfavoriteArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnfavoriteArticleRequest proto.InternalMessageInfo

func (m *UnfavoriteArticleRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type DeleteCommentRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentRequest) Reset()         { *m = DeleteCommentRequest{} }
func (m *DeleteCommentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentRequest) ProtoMessage()    {}
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{3}
}

func (m *DeleteCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentRequest.Unmarshal(m, b)
}
func (m *DeleteCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentRequest.Merge(m, src)
}
func (m *DeleteCommentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentRequest.Size(m)
}
func (m *DeleteCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentRequest proto.InternalMessageInfo

func (m *DeleteCommentRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *DeleteCommentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AddCommentRequest struct {
	Comment              *AddCommentRequest_Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Slug                 string                     `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AddCommentRequest) Reset()         { *m = AddCommentRequest{} }
func (m *AddCommentRequest) String() string { return proto.CompactTextString(m) }
func (*AddCommentRequest) ProtoMessage()    {}
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{4}
}

func (m *AddCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommentRequest.Unmarshal(m, b)
}
func (m *AddCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommentRequest.Marshal(b, m, deterministic)
}
func (m *AddCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommentRequest.Merge(m, src)
}
func (m *AddCommentRequest) XXX_Size() int {
	return xxx_messageInfo_AddCommentRequest.Size(m)
}
func (m *AddCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommentRequest proto.InternalMessageInfo

func (m *AddCommentRequest) GetComment() *AddCommentRequest_Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *AddCommentRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type AddCommentRequest_Comment struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCommentRequest_Comment) Reset()         { *m = AddCommentRequest_Comment{} }
func (m *AddCommentRequest_Comment) String() string { return proto.CompactTextString(m) }
func (*AddCommentRequest_Comment) ProtoMessage()    {}
func (*AddCommentRequest_Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{4, 0}
}

func (m *AddCommentRequest_Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommentRequest_Comment.Unmarshal(m, b)
}
func (m *AddCommentRequest_Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommentRequest_Comment.Marshal(b, m, deterministic)
}
func (m *AddCommentRequest_Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommentRequest_Comment.Merge(m, src)
}
func (m *AddCommentRequest_Comment) XXX_Size() int {
	return xxx_messageInfo_AddCommentRequest_Comment.Size(m)
}
func (m *AddCommentRequest_Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommentRequest_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommentRequest_Comment proto.InternalMessageInfo

func (m *AddCommentRequest_Comment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type DeleteArticleRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteArticleRequest) Reset()         { *m = DeleteArticleRequest{} }
func (m *DeleteArticleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteArticleRequest) ProtoMessage()    {}
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{5}
}

func (m *DeleteArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteArticleRequest.Unmarshal(m, b)
}
func (m *DeleteArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteArticleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteArticleRequest.Merge(m, src)
}
func (m *DeleteArticleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteArticleRequest.Size(m)
}
func (m *DeleteArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteArticleRequest proto.InternalMessageInfo

func (m *DeleteArticleRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type UpdateArticleRequest struct {
	Article              *UpdateArticleRequest_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Slug                 string                        `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UpdateArticleRequest) Reset()         { *m = UpdateArticleRequest{} }
func (m *UpdateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateArticleRequest) ProtoMessage()    {}
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{6}
}

func (m *UpdateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateArticleRequest.Unmarshal(m, b)
}
func (m *UpdateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateArticleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateArticleRequest.Merge(m, src)
}
func (m *UpdateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateArticleRequest.Size(m)
}
func (m *UpdateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateArticleRequest proto.InternalMessageInfo

func (m *UpdateArticleRequest) GetArticle() *UpdateArticleRequest_Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func (m *UpdateArticleRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type UpdateArticleRequest_Article struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TagList              []string `protobuf:"bytes,4,rep,name=tagList,proto3" json:"tagList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateArticleRequest_Article) Reset()         { *m = UpdateArticleRequest_Article{} }
func (m *UpdateArticleRequest_Article) String() string { return proto.CompactTextString(m) }
func (*UpdateArticleRequest_Article) ProtoMessage()    {}
func (*UpdateArticleRequest_Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{6, 0}
}

func (m *UpdateArticleRequest_Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateArticleRequest_Article.Unmarshal(m, b)
}
func (m *UpdateArticleRequest_Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateArticleRequest_Article.Marshal(b, m, deterministic)
}
func (m *UpdateArticleRequest_Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateArticleRequest_Article.Merge(m, src)
}
func (m *UpdateArticleRequest_Article) XXX_Size() int {
	return xxx_messageInfo_UpdateArticleRequest_Article.Size(m)
}
func (m *UpdateArticleRequest_Article) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateArticleRequest_Article.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateArticleRequest_Article proto.InternalMessageInfo

func (m *UpdateArticleRequest_Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateArticleRequest_Article) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateArticleRequest_Article) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *UpdateArticleRequest_Article) GetTagList() []string {
	if m != nil {
		return m.TagList
	}
	return nil
}

type CreateArticleRequest struct {
	Article              *CreateArticleRequest_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateArticleRequest) Reset()         { *m = CreateArticleRequest{} }
func (m *CreateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateArticleRequest) ProtoMessage()    {}
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{7}
}

func (m *CreateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleRequest.Unmarshal(m, b)
}
func (m *CreateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleRequest.Marshal(b, m, deterministic)
}
func (m *CreateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleRequest.Merge(m, src)
}
func (m *CreateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateArticleRequest.Size(m)
}
func (m *CreateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleRequest proto.InternalMessageInfo

func (m *CreateArticleRequest) GetArticle() *CreateArticleRequest_Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type CreateArticleRequest_Article struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TagList              []string `protobuf:"bytes,4,rep,name=tagList,proto3" json:"tagList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleRequest_Article) Reset()         { *m = CreateArticleRequest_Article{} }
func (m *CreateArticleRequest_Article) String() string { return proto.CompactTextString(m) }
func (*CreateArticleRequest_Article) ProtoMessage()    {}
func (*CreateArticleRequest_Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{7, 0}
}

func (m *CreateArticleRequest_Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleRequest_Article.Unmarshal(m, b)
}
func (m *CreateArticleRequest_Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleRequest_Article.Marshal(b, m, deterministic)
}
func (m *CreateArticleRequest_Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleRequest_Article.Merge(m, src)
}
func (m *CreateArticleRequest_Article) XXX_Size() int {
	return xxx_messageInfo_CreateArticleRequest_Article.Size(m)
}
func (m *CreateArticleRequest_Article) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleRequest_Article.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleRequest_Article proto.InternalMessageInfo

func (m *CreateArticleRequest_Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateArticleRequest_Article) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateArticleRequest_Article) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateArticleRequest_Article) GetTagList() []string {
	if m != nil {
		return m.TagList
	}
	return nil
}

type GetArticleRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleRequest) Reset()         { *m = GetArticleRequest{} }
func (m *GetArticleRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleRequest) ProtoMessage()    {}
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{8}
}

func (m *GetArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleRequest.Unmarshal(m, b)
}
func (m *GetArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleRequest.Merge(m, src)
}
func (m *GetArticleRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleRequest.Size(m)
}
func (m *GetArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleRequest proto.InternalMessageInfo

func (m *GetArticleRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type FeedArticlesRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedArticlesRequest) Reset()         { *m = FeedArticlesRequest{} }
func (m *FeedArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*FeedArticlesRequest) ProtoMessage()    {}
func (*FeedArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{9}
}

func (m *FeedArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedArticlesRequest.Unmarshal(m, b)
}
func (m *FeedArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedArticlesRequest.Marshal(b, m, deterministic)
}
func (m *FeedArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedArticlesRequest.Merge(m, src)
}
func (m *FeedArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_FeedArticlesRequest.Size(m)
}
func (m *FeedArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedArticlesRequest proto.InternalMessageInfo

func (m *FeedArticlesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FeedArticlesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListArticlesRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Favorited            string   `protobuf:"bytes,3,opt,name=favorited,proto3" json:"favorited,omitempty"`
	Limit                int64    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticlesRequest) Reset()         { *m = ListArticlesRequest{} }
func (m *ListArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*ListArticlesRequest) ProtoMessage()    {}
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{10}
}

func (m *ListArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticlesRequest.Unmarshal(m, b)
}
func (m *ListArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticlesRequest.Marshal(b, m, deterministic)
}
func (m *ListArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticlesRequest.Merge(m, src)
}
func (m *ListArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_ListArticlesRequest.Size(m)
}
func (m *ListArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticlesRequest proto.InternalMessageInfo

func (m *ListArticlesRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ListArticlesRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ListArticlesRequest) GetFavorited() string {
	if m != nil {
		return m.Favorited
	}
	return ""
}

func (m *ListArticlesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListArticlesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type UnfollowUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfollowUserRequest) Reset()         { *m = UnfollowUserRequest{} }
func (m *UnfollowUserRequest) String() string { return proto.CompactTextString(m) }
func (*UnfollowUserRequest) ProtoMessage()    {}
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{11}
}

func (m *UnfollowUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfollowUserRequest.Unmarshal(m, b)
}
func (m *UnfollowUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfollowUserRequest.Marshal(b, m, deterministic)
}
func (m *UnfollowUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfollowUserRequest.Merge(m, src)
}
func (m *UnfollowUserRequest) XXX_Size() int {
	return xxx_messageInfo_UnfollowUserRequest.Size(m)
}
func (m *UnfollowUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfollowUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnfollowUserRequest proto.InternalMessageInfo

func (m *UnfollowUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type FollowUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowUserRequest) Reset()         { *m = FollowUserRequest{} }
func (m *FollowUserRequest) String() string { return proto.CompactTextString(m) }
func (*FollowUserRequest) ProtoMessage()    {}
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{12}
}

func (m *FollowUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowUserRequest.Unmarshal(m, b)
}
func (m *FollowUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowUserRequest.Marshal(b, m, deterministic)
}
func (m *FollowUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowUserRequest.Merge(m, src)
}
func (m *FollowUserRequest) XXX_Size() int {
	return xxx_messageInfo_FollowUserRequest.Size(m)
}
func (m *FollowUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowUserRequest proto.InternalMessageInfo

func (m *FollowUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetProfileRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{13}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetCurrentUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentUserRequest) Reset()         { *m = GetCurrentUserRequest{} }
func (m *GetCurrentUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrentUserRequest) ProtoMessage()    {}
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{14}
}

func (m *GetCurrentUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentUserRequest.Unmarshal(m, b)
}
func (m *GetCurrentUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentUserRequest.Marshal(b, m, deterministic)
}
func (m *GetCurrentUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentUserRequest.Merge(m, src)
}
func (m *GetCurrentUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrentUserRequest.Size(m)
}
func (m *GetCurrentUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentUserRequest proto.InternalMessageInfo

type UpdateUserRequest struct {
	User                 *UpdateUserRequest_User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{15}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *UpdateUserRequest_User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest_User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest_User) Reset()         { *m = UpdateUserRequest_User{} }
func (m *UpdateUserRequest_User) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest_User) ProtoMessage()    {}
func (*UpdateUserRequest_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{15, 0}
}

func (m *UpdateUserRequest_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest_User.Unmarshal(m, b)
}
func (m *UpdateUserRequest_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest_User.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest_User.Merge(m, src)
}
func (m *UpdateUserRequest_User) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest_User.Size(m)
}
func (m *UpdateUserRequest_User) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest_User.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest_User proto.InternalMessageInfo

func (m *UpdateUserRequest_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest_User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateUserRequest_User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest_User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UpdateUserRequest_User) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type UserReply struct {
	User                 *UserReply_User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserReply) Reset()         { *m = UserReply{} }
func (m *UserReply) String() string { return proto.CompactTextString(m) }
func (*UserReply) ProtoMessage()    {}
func (*UserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{16}
}

func (m *UserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReply.Unmarshal(m, b)
}
func (m *UserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReply.Marshal(b, m, deterministic)
}
func (m *UserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReply.Merge(m, src)
}
func (m *UserReply) XXX_Size() int {
	return xxx_messageInfo_UserReply.Size(m)
}
func (m *UserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserReply proto.InternalMessageInfo

func (m *UserReply) GetUser() *UserReply_User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserReply_User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReply_User) Reset()         { *m = UserReply_User{} }
func (m *UserReply_User) String() string { return proto.CompactTextString(m) }
func (*UserReply_User) ProtoMessage()    {}
func (*UserReply_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{16, 0}
}

func (m *UserReply_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReply_User.Unmarshal(m, b)
}
func (m *UserReply_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReply_User.Marshal(b, m, deterministic)
}
func (m *UserReply_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReply_User.Merge(m, src)
}
func (m *UserReply_User) XXX_Size() int {
	return xxx_messageInfo_UserReply_User.Size(m)
}
func (m *UserReply_User) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReply_User.DiscardUnknown(m)
}

var xxx_messageInfo_UserReply_User proto.InternalMessageInfo

func (m *UserReply_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserReply_User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserReply_User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserReply_User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UserReply_User) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ProfileReply struct {
	Profile              *ProfileReply_Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProfileReply) Reset()         { *m = ProfileReply{} }
func (m *ProfileReply) String() string { return proto.CompactTextString(m) }
func (*ProfileReply) ProtoMessage()    {}
func (*ProfileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{17}
}

func (m *ProfileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileReply.Unmarshal(m, b)
}
func (m *ProfileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileReply.Marshal(b, m, deterministic)
}
func (m *ProfileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileReply.Merge(m, src)
}
func (m *ProfileReply) XXX_Size() int {
	return xxx_messageInfo_ProfileReply.Size(m)
}
func (m *ProfileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileReply proto.InternalMessageInfo

func (m *ProfileReply) GetProfile() *ProfileReply_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type ProfileReply_Profile struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio                  string   `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following            bool     `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileReply_Profile) Reset()         { *m = ProfileReply_Profile{} }
func (m *ProfileReply_Profile) String() string { return proto.CompactTextString(m) }
func (*ProfileReply_Profile) ProtoMessage()    {}
func (*ProfileReply_Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{17, 0}
}

func (m *ProfileReply_Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileReply_Profile.Unmarshal(m, b)
}
func (m *ProfileReply_Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileReply_Profile.Marshal(b, m, deterministic)
}
func (m *ProfileReply_Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileReply_Profile.Merge(m, src)
}
func (m *ProfileReply_Profile) XXX_Size() int {
	return xxx_messageInfo_ProfileReply_Profile.Size(m)
}
func (m *ProfileReply_Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileReply_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileReply_Profile proto.InternalMessageInfo

func (m *ProfileReply_Profile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProfileReply_Profile) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *ProfileReply_Profile) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ProfileReply_Profile) GetFollowing() bool {
	if m != nil {
		return m.Following
	}
	return false
}

type SingleArticleReply struct {
	Article              *SingleArticleReply_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SingleArticleReply) Reset()         { *m = SingleArticleReply{} }
func (m *SingleArticleReply) String() string { return proto.CompactTextString(m) }
func (*SingleArticleReply) ProtoMessage()    {}
func (*SingleArticleReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{18}
}

func (m *SingleArticleReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleArticleReply.Unmarshal(m, b)
}
func (m *SingleArticleReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleArticleReply.Marshal(b, m, deterministic)
}
func (m *SingleArticleReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleArticleReply.Merge(m, src)
}
func (m *SingleArticleReply) XXX_Size() int {
	return xxx_messageInfo_SingleArticleReply.Size(m)
}
func (m *SingleArticleReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleArticleReply.DiscardUnknown(m)
}

var xxx_messageInfo_SingleArticleReply proto.InternalMessageInfo

func (m *SingleArticleReply) GetArticle() *SingleArticleReply_Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type SingleArticleReply_Author struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio                  string   `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following            bool     `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleArticleReply_Author) Reset()         { *m = SingleArticleReply_Author{} }
func (m *SingleArticleReply_Author) String() string { return proto.CompactTextString(m) }
func (*SingleArticleReply_Author) ProtoMessage()    {}
func (*SingleArticleReply_Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{18, 0}
}

func (m *SingleArticleReply_Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleArticleReply_Author.Unmarshal(m, b)
}
func (m *SingleArticleReply_Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleArticleReply_Author.Marshal(b, m, deterministic)
}
func (m *SingleArticleReply_Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleArticleReply_Author.Merge(m, src)
}
func (m *SingleArticleReply_Author) XXX_Size() int {
	return xxx_messageInfo_SingleArticleReply_Author.Size(m)
}
func (m *SingleArticleReply_Author) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleArticleReply_Author.DiscardUnknown(m)
}

var xxx_messageInfo_SingleArticleReply_Author proto.InternalMessageInfo

func (m *SingleArticleReply_Author) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SingleArticleReply_Author) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *SingleArticleReply_Author) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *SingleArticleReply_Author) GetFollowing() bool {
	if m != nil {
		return m.Following
	}
	return false
}

type SingleArticleReply_Article struct {
	Slug                 string                     `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title                string                     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Body                 string                     `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TagList              []string                   `protobuf:"bytes,5,rep,name=tagList,proto3" json:"tagList,omitempty"`
	CreatedAt            string                     `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string                     `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Favorited            bool                       `protobuf:"varint,8,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoritesCount       uint32                     `protobuf:"varint,9,opt,name=favoritesCount,proto3" json:"favoritesCount,omitempty"`
	Author               *SingleArticleReply_Author `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SingleArticleReply_Article) Reset()         { *m = SingleArticleReply_Article{} }
func (m *SingleArticleReply_Article) String() string { return proto.CompactTextString(m) }
func (*SingleArticleReply_Article) ProtoMessage()    {}
func (*SingleArticleReply_Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{18, 1}
}

func (m *SingleArticleReply_Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleArticleReply_Article.Unmarshal(m, b)
}
func (m *SingleArticleReply_Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleArticleReply_Article.Marshal(b, m, deterministic)
}
func (m *SingleArticleReply_Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleArticleReply_Article.Merge(m, src)
}
func (m *SingleArticleReply_Article) XXX_Size() int {
	return xxx_messageInfo_SingleArticleReply_Article.Size(m)
}
func (m *SingleArticleReply_Article) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleArticleReply_Article.DiscardUnknown(m)
}

var xxx_messageInfo_SingleArticleReply_Article proto.InternalMessageInfo

func (m *SingleArticleReply_Article) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *SingleArticleReply_Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SingleArticleReply_Article) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SingleArticleReply_Article) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *SingleArticleReply_Article) GetTagList() []string {
	if m != nil {
		return m.TagList
	}
	return nil
}

func (m *SingleArticleReply_Article) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *SingleArticleReply_Article) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *SingleArticleReply_Article) GetFavorited() bool {
	if m != nil {
		return m.Favorited
	}
	return false
}

func (m *SingleArticleReply_Article) GetFavoritesCount() uint32 {
	if m != nil {
		return m.FavoritesCount
	}
	return 0
}

func (m *SingleArticleReply_Article) GetAuthor() *SingleArticleReply_Author {
	if m != nil {
		return m.Author
	}
	return nil
}

type MultipleArticlesReply struct {
	Articles             []*MultipleArticlesReply_Articles `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	ArticlesCount        uint32                            `protobuf:"varint,2,opt,name=articlesCount,proto3" json:"articlesCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *MultipleArticlesReply) Reset()         { *m = MultipleArticlesReply{} }
func (m *MultipleArticlesReply) String() string { return proto.CompactTextString(m) }
func (*MultipleArticlesReply) ProtoMessage()    {}
func (*MultipleArticlesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{19}
}

func (m *MultipleArticlesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleArticlesReply.Unmarshal(m, b)
}
func (m *MultipleArticlesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleArticlesReply.Marshal(b, m, deterministic)
}
func (m *MultipleArticlesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleArticlesReply.Merge(m, src)
}
func (m *MultipleArticlesReply) XXX_Size() int {
	return xxx_messageInfo_MultipleArticlesReply.Size(m)
}
func (m *MultipleArticlesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleArticlesReply.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleArticlesReply proto.InternalMessageInfo

func (m *MultipleArticlesReply) GetArticles() []*MultipleArticlesReply_Articles {
	if m != nil {
		return m.Articles
	}
	return nil
}

func (m *MultipleArticlesReply) GetArticlesCount() uint32 {
	if m != nil {
		return m.ArticlesCount
	}
	return 0
}

type MultipleArticlesReply_Author struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio                  string   `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following            bool     `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultipleArticlesReply_Author) Reset()         { *m = MultipleArticlesReply_Author{} }
func (m *MultipleArticlesReply_Author) String() string { return proto.CompactTextString(m) }
func (*MultipleArticlesReply_Author) ProtoMessage()    {}
func (*MultipleArticlesReply_Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{19, 0}
}

func (m *MultipleArticlesReply_Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleArticlesReply_Author.Unmarshal(m, b)
}
func (m *MultipleArticlesReply_Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleArticlesReply_Author.Marshal(b, m, deterministic)
}
func (m *MultipleArticlesReply_Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleArticlesReply_Author.Merge(m, src)
}
func (m *MultipleArticlesReply_Author) XXX_Size() int {
	return xxx_messageInfo_MultipleArticlesReply_Author.Size(m)
}
func (m *MultipleArticlesReply_Author) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleArticlesReply_Author.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleArticlesReply_Author proto.InternalMessageInfo

func (m *MultipleArticlesReply_Author) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MultipleArticlesReply_Author) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *MultipleArticlesReply_Author) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MultipleArticlesReply_Author) GetFollowing() bool {
	if m != nil {
		return m.Following
	}
	return false
}

type MultipleArticlesReply_Articles struct {
	Slug                 string                        `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title                string                        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Body                 string                        `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TagList              []string                      `protobuf:"bytes,5,rep,name=tagList,proto3" json:"tagList,omitempty"`
	CreatedAt            string                        `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string                        `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Favorited            bool                          `protobuf:"varint,8,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoritesCount       uint32                        `protobuf:"varint,9,opt,name=favoritesCount,proto3" json:"favoritesCount,omitempty"`
	Author               *MultipleArticlesReply_Author `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MultipleArticlesReply_Articles) Reset()         { *m = MultipleArticlesReply_Articles{} }
func (m *MultipleArticlesReply_Articles) String() string { return proto.CompactTextString(m) }
func (*MultipleArticlesReply_Articles) ProtoMessage()    {}
func (*MultipleArticlesReply_Articles) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{19, 1}
}

func (m *MultipleArticlesReply_Articles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleArticlesReply_Articles.Unmarshal(m, b)
}
func (m *MultipleArticlesReply_Articles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleArticlesReply_Articles.Marshal(b, m, deterministic)
}
func (m *MultipleArticlesReply_Articles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleArticlesReply_Articles.Merge(m, src)
}
func (m *MultipleArticlesReply_Articles) XXX_Size() int {
	return xxx_messageInfo_MultipleArticlesReply_Articles.Size(m)
}
func (m *MultipleArticlesReply_Articles) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleArticlesReply_Articles.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleArticlesReply_Articles proto.InternalMessageInfo

func (m *MultipleArticlesReply_Articles) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *MultipleArticlesReply_Articles) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MultipleArticlesReply_Articles) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MultipleArticlesReply_Articles) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MultipleArticlesReply_Articles) GetTagList() []string {
	if m != nil {
		return m.TagList
	}
	return nil
}

func (m *MultipleArticlesReply_Articles) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MultipleArticlesReply_Articles) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *MultipleArticlesReply_Articles) GetFavorited() bool {
	if m != nil {
		return m.Favorited
	}
	return false
}

func (m *MultipleArticlesReply_Articles) GetFavoritesCount() uint32 {
	if m != nil {
		return m.FavoritesCount
	}
	return 0
}

func (m *MultipleArticlesReply_Articles) GetAuthor() *MultipleArticlesReply_Author {
	if m != nil {
		return m.Author
	}
	return nil
}

type SingleCommentReply struct {
	Comment              *SingleCommentReply_Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SingleCommentReply) Reset()         { *m = SingleCommentReply{} }
func (m *SingleCommentReply) String() string { return proto.CompactTextString(m) }
func (*SingleCommentReply) ProtoMessage()    {}
func (*SingleCommentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{20}
}

func (m *SingleCommentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleCommentReply.Unmarshal(m, b)
}
func (m *SingleCommentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleCommentReply.Marshal(b, m, deterministic)
}
func (m *SingleCommentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleCommentReply.Merge(m, src)
}
func (m *SingleCommentReply) XXX_Size() int {
	return xxx_messageInfo_SingleCommentReply.Size(m)
}
func (m *SingleCommentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleCommentReply.DiscardUnknown(m)
}

var xxx_messageInfo_SingleCommentReply proto.InternalMessageInfo

func (m *SingleCommentReply) GetComment() *SingleCommentReply_Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type SingleCommentReply_Author struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio                  string   `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following            bool     `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleCommentReply_Author) Reset()         { *m = SingleCommentReply_Author{} }
func (m *SingleCommentReply_Author) String() string { return proto.CompactTextString(m) }
func (*SingleCommentReply_Author) ProtoMessage()    {}
func (*SingleCommentReply_Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{20, 0}
}

func (m *SingleCommentReply_Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleCommentReply_Author.Unmarshal(m, b)
}
func (m *SingleCommentReply_Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleCommentReply_Author.Marshal(b, m, deterministic)
}
func (m *SingleCommentReply_Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleCommentReply_Author.Merge(m, src)
}
func (m *SingleCommentReply_Author) XXX_Size() int {
	return xxx_messageInfo_SingleCommentReply_Author.Size(m)
}
func (m *SingleCommentReply_Author) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleCommentReply_Author.DiscardUnknown(m)
}

var xxx_messageInfo_SingleCommentReply_Author proto.InternalMessageInfo

func (m *SingleCommentReply_Author) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SingleCommentReply_Author) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *SingleCommentReply_Author) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *SingleCommentReply_Author) GetFollowing() bool {
	if m != nil {
		return m.Following
	}
	return false
}

type SingleCommentReply_Comment struct {
	Id                   uint32                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string                     `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string                     `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Body                 string                     `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author               *SingleCommentReply_Author `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SingleCommentReply_Comment) Reset()         { *m = SingleCommentReply_Comment{} }
func (m *SingleCommentReply_Comment) String() string { return proto.CompactTextString(m) }
func (*SingleCommentReply_Comment) ProtoMessage()    {}
func (*SingleCommentReply_Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{20, 1}
}

func (m *SingleCommentReply_Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleCommentReply_Comment.Unmarshal(m, b)
}
func (m *SingleCommentReply_Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleCommentReply_Comment.Marshal(b, m, deterministic)
}
func (m *SingleCommentReply_Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleCommentReply_Comment.Merge(m, src)
}
func (m *SingleCommentReply_Comment) XXX_Size() int {
	return xxx_messageInfo_SingleCommentReply_Comment.Size(m)
}
func (m *SingleCommentReply_Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleCommentReply_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_SingleCommentReply_Comment proto.InternalMessageInfo

func (m *SingleCommentReply_Comment) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SingleCommentReply_Comment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *SingleCommentReply_Comment) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *SingleCommentReply_Comment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *SingleCommentReply_Comment) GetAuthor() *SingleCommentReply_Author {
	if m != nil {
		return m.Author
	}
	return nil
}

type MultipleCommentsReply struct {
	Comments             []*MultipleCommentsReply_Comments `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *MultipleCommentsReply) Reset()         { *m = MultipleCommentsReply{} }
func (m *MultipleCommentsReply) String() string { return proto.CompactTextString(m) }
func (*MultipleCommentsReply) ProtoMessage()    {}
func (*MultipleCommentsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{21}
}

func (m *MultipleCommentsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleCommentsReply.Unmarshal(m, b)
}
func (m *MultipleCommentsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleCommentsReply.Marshal(b, m, deterministic)
}
func (m *MultipleCommentsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleCommentsReply.Merge(m, src)
}
func (m *MultipleCommentsReply) XXX_Size() int {
	return xxx_messageInfo_MultipleCommentsReply.Size(m)
}
func (m *MultipleCommentsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleCommentsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleCommentsReply proto.InternalMessageInfo

func (m *MultipleCommentsReply) GetComments() []*MultipleCommentsReply_Comments {
	if m != nil {
		return m.Comments
	}
	return nil
}

type MultipleCommentsReply_Author struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio                  string   `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following            bool     `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultipleCommentsReply_Author) Reset()         { *m = MultipleCommentsReply_Author{} }
func (m *MultipleCommentsReply_Author) String() string { return proto.CompactTextString(m) }
func (*MultipleCommentsReply_Author) ProtoMessage()    {}
func (*MultipleCommentsReply_Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{21, 0}
}

func (m *MultipleCommentsReply_Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleCommentsReply_Author.Unmarshal(m, b)
}
func (m *MultipleCommentsReply_Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleCommentsReply_Author.Marshal(b, m, deterministic)
}
func (m *MultipleCommentsReply_Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleCommentsReply_Author.Merge(m, src)
}
func (m *MultipleCommentsReply_Author) XXX_Size() int {
	return xxx_messageInfo_MultipleCommentsReply_Author.Size(m)
}
func (m *MultipleCommentsReply_Author) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleCommentsReply_Author.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleCommentsReply_Author proto.InternalMessageInfo

func (m *MultipleCommentsReply_Author) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MultipleCommentsReply_Author) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *MultipleCommentsReply_Author) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MultipleCommentsReply_Author) GetFollowing() bool {
	if m != nil {
		return m.Following
	}
	return false
}

type MultipleCommentsReply_Comments struct {
	Id                   uint32                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string                        `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string                        `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Body                 string                        `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author               *MultipleCommentsReply_Author `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MultipleCommentsReply_Comments) Reset()         { *m = MultipleCommentsReply_Comments{} }
func (m *MultipleCommentsReply_Comments) String() string { return proto.CompactTextString(m) }
func (*MultipleCommentsReply_Comments) ProtoMessage()    {}
func (*MultipleCommentsReply_Comments) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{21, 1}
}

func (m *MultipleCommentsReply_Comments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleCommentsReply_Comments.Unmarshal(m, b)
}
func (m *MultipleCommentsReply_Comments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleCommentsReply_Comments.Marshal(b, m, deterministic)
}
func (m *MultipleCommentsReply_Comments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleCommentsReply_Comments.Merge(m, src)
}
func (m *MultipleCommentsReply_Comments) XXX_Size() int {
	return xxx_messageInfo_MultipleCommentsReply_Comments.Size(m)
}
func (m *MultipleCommentsReply_Comments) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleCommentsReply_Comments.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleCommentsReply_Comments proto.InternalMessageInfo

func (m *MultipleCommentsReply_Comments) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MultipleCommentsReply_Comments) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MultipleCommentsReply_Comments) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *MultipleCommentsReply_Comments) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MultipleCommentsReply_Comments) GetAuthor() *MultipleCommentsReply_Author {
	if m != nil {
		return m.Author
	}
	return nil
}

type TagListReply struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagListReply) Reset()         { *m = TagListReply{} }
func (m *TagListReply) String() string { return proto.CompactTextString(m) }
func (*TagListReply) ProtoMessage()    {}
func (*TagListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{22}
}

func (m *TagListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagListReply.Unmarshal(m, b)
}
func (m *TagListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagListReply.Marshal(b, m, deterministic)
}
func (m *TagListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagListReply.Merge(m, src)
}
func (m *TagListReply) XXX_Size() int {
	return xxx_messageInfo_TagListReply.Size(m)
}
func (m *TagListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TagListReply.DiscardUnknown(m)
}

var xxx_messageInfo_TagListReply proto.InternalMessageInfo

func (m *TagListReply) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type LoginRequest struct {
	User                 *LoginRequest_User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{23}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUser() *LoginRequest_User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginRequest_User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest_User) Reset()         { *m = LoginRequest_User{} }
func (m *LoginRequest_User) String() string { return proto.CompactTextString(m) }
func (*LoginRequest_User) ProtoMessage()    {}
func (*LoginRequest_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{23, 0}
}

func (m *LoginRequest_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest_User.Unmarshal(m, b)
}
func (m *LoginRequest_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest_User.Marshal(b, m, deterministic)
}
func (m *LoginRequest_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest_User.Merge(m, src)
}
func (m *LoginRequest_User) XXX_Size() int {
	return xxx_messageInfo_LoginRequest_User.Size(m)
}
func (m *LoginRequest_User) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest_User.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest_User proto.InternalMessageInfo

func (m *LoginRequest_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest_User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterRequest struct {
	User                 *RegisterRequest_User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{24}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUser() *RegisterRequest_User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterRequest_User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest_User) Reset()         { *m = RegisterRequest_User{} }
func (m *RegisterRequest_User) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest_User) ProtoMessage()    {}
func (*RegisterRequest_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56e4f58b20064f, []int{24, 0}
}

func (m *RegisterRequest_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest_User.Unmarshal(m, b)
}
func (m *RegisterRequest_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest_User.Marshal(b, m, deterministic)
}
func (m *RegisterRequest_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest_User.Merge(m, src)
}
func (m *RegisterRequest_User) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest_User.Size(m)
}
func (m *RegisterRequest_User) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest_User.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest_User proto.InternalMessageInfo

func (m *RegisterRequest_User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest_User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest_User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTagsRequest)(nil), "realworld.v1.GetTagsRequest")
	proto.RegisterType((*FavoriteArticleRequest)(nil), "realworld.v1.FavoriteArticleRequest")
	proto.RegisterType((*UnfavoriteArticleRequest)(nil), "realworld.v1.UnfavoriteArticleRequest")
	proto.RegisterType((*DeleteCommentRequest)(nil), "realworld.v1.DeleteCommentRequest")
	proto.RegisterType((*AddCommentRequest)(nil), "realworld.v1.AddCommentRequest")
	proto.RegisterType((*AddCommentRequest_Comment)(nil), "realworld.v1.AddCommentRequest.Comment")
	proto.RegisterType((*DeleteArticleRequest)(nil), "realworld.v1.DeleteArticleRequest")
	proto.RegisterType((*UpdateArticleRequest)(nil), "realworld.v1.UpdateArticleRequest")
	proto.RegisterType((*UpdateArticleRequest_Article)(nil), "realworld.v1.UpdateArticleRequest.Article")
	proto.RegisterType((*CreateArticleRequest)(nil), "realworld.v1.CreateArticleRequest")
	proto.RegisterType((*CreateArticleRequest_Article)(nil), "realworld.v1.CreateArticleRequest.Article")
	proto.RegisterType((*GetArticleRequest)(nil), "realworld.v1.GetArticleRequest")
	proto.RegisterType((*FeedArticlesRequest)(nil), "realworld.v1.FeedArticlesRequest")
	proto.RegisterType((*ListArticlesRequest)(nil), "realworld.v1.ListArticlesRequest")
	proto.RegisterType((*UnfollowUserRequest)(nil), "realworld.v1.UnfollowUserRequest")
	proto.RegisterType((*FollowUserRequest)(nil), "realworld.v1.FollowUserRequest")
	proto.RegisterType((*GetProfileRequest)(nil), "realworld.v1.GetProfileRequest")
	proto.RegisterType((*GetCurrentUserRequest)(nil), "realworld.v1.GetCurrentUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "realworld.v1.UpdateUserRequest")
	proto.RegisterType((*UpdateUserRequest_User)(nil), "realworld.v1.UpdateUserRequest.User")
	proto.RegisterType((*UserReply)(nil), "realworld.v1.UserReply")
	proto.RegisterType((*UserReply_User)(nil), "realworld.v1.UserReply.User")
	proto.RegisterType((*ProfileReply)(nil), "realworld.v1.ProfileReply")
	proto.RegisterType((*ProfileReply_Profile)(nil), "realworld.v1.ProfileReply.Profile")
	proto.RegisterType((*SingleArticleReply)(nil), "realworld.v1.SingleArticleReply")
	proto.RegisterType((*SingleArticleReply_Author)(nil), "realworld.v1.SingleArticleReply.Author")
	proto.RegisterType((*SingleArticleReply_Article)(nil), "realworld.v1.SingleArticleReply.Article")
	proto.RegisterType((*MultipleArticlesReply)(nil), "realworld.v1.MultipleArticlesReply")
	proto.RegisterType((*MultipleArticlesReply_Author)(nil), "realworld.v1.MultipleArticlesReply.Author")
	proto.RegisterType((*MultipleArticlesReply_Articles)(nil), "realworld.v1.MultipleArticlesReply.Articles")
	proto.RegisterType((*SingleCommentReply)(nil), "realworld.v1.SingleCommentReply")
	proto.RegisterType((*SingleCommentReply_Author)(nil), "realworld.v1.SingleCommentReply.Author")
	proto.RegisterType((*SingleCommentReply_Comment)(nil), "realworld.v1.SingleCommentReply.Comment")
	proto.RegisterType((*MultipleCommentsReply)(nil), "realworld.v1.MultipleCommentsReply")
	proto.RegisterType((*MultipleCommentsReply_Author)(nil), "realworld.v1.MultipleCommentsReply.Author")
	proto.RegisterType((*MultipleCommentsReply_Comments)(nil), "realworld.v1.MultipleCommentsReply.Comments")
	proto.RegisterType((*TagListReply)(nil), "realworld.v1.TagListReply")
	proto.RegisterType((*LoginRequest)(nil), "realworld.v1.LoginRequest")
	proto.RegisterType((*LoginRequest_User)(nil), "realworld.v1.LoginRequest.User")
	proto.RegisterType((*RegisterRequest)(nil), "realworld.v1.RegisterRequest")
	proto.RegisterType((*RegisterRequest_User)(nil), "realworld.v1.RegisterRequest.User")
}

func init() { proto.RegisterFile("api/realworld/v1/realworld.proto", fileDescriptor_7f56e4f58b20064f) }

var fileDescriptor_7f56e4f58b20064f = []byte{
	// 1511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x59, 0x4f, 0x6f, 0xdb, 0xc6,
	0x12, 0x07, 0x29, 0xd9, 0x92, 0xc6, 0xb2, 0x63, 0x6f, 0xe4, 0x44, 0x8f, 0xcf, 0x81, 0x95, 0x8d,
	0x5f, 0x22, 0x08, 0x79, 0xd2, 0x73, 0x02, 0x3c, 0x04, 0x69, 0x81, 0xc2, 0x76, 0x10, 0xf7, 0x90,
	0x02, 0x05, 0x1b, 0xb7, 0x48, 0xd1, 0x0b, 0x63, 0xae, 0x55, 0xd6, 0x94, 0xa8, 0x92, 0x2b, 0x07,
	0x69, 0xe0, 0x43, 0xff, 0x5c, 0x8a, 0xa2, 0xa7, 0x7e, 0x80, 0xde, 0x7b, 0xe8, 0xad, 0x87, 0xde,
	0x7a, 0x69, 0x0f, 0x05, 0x7a, 0xea, 0x27, 0x28, 0xd0, 0x73, 0x81, 0x7e, 0x81, 0xa2, 0xd8, 0xe5,
	0x2e, 0xc9, 0x5d, 0x52, 0xb4, 0x52, 0x20, 0x46, 0x81, 0xde, 0x76, 0x96, 0x3b, 0xfb, 0xfb, 0xcd,
	0xec, 0xec, 0x68, 0x76, 0x04, 0x1d, 0x67, 0xe2, 0x0d, 0x42, 0xe2, 0xf8, 0x4f, 0x82, 0xd0, 0x77,
	0x07, 0x27, 0xdb, 0xa9, 0xd0, 0x9f, 0x84, 0x01, 0x0d, 0x50, 0x33, 0x9d, 0x38, 0xd9, 0xb6, 0x36,
	0x86, 0x41, 0x30, 0xf4, 0xc9, 0x80, 0xa9, 0x39, 0xe3, 0x71, 0x40, 0x1d, 0xea, 0x05, 0xe3, 0x28,
	0x5e, 0x8b, 0x57, 0x61, 0x65, 0x9f, 0xd0, 0x87, 0xce, 0x30, 0xb2, 0xc9, 0xfb, 0x53, 0x12, 0x51,
	0x7c, 0x13, 0x2e, 0xdd, 0x77, 0x4e, 0x82, 0xd0, 0xa3, 0x64, 0x27, 0xa4, 0xde, 0xa1, 0x4f, 0xc4,
	0x17, 0x84, 0xa0, 0x1a, 0xf9, 0xd3, 0x61, 0xdb, 0xe8, 0x18, 0xdd, 0x86, 0xcd, 0xc7, 0xb8, 0x0f,
	0xed, 0x83, 0xf1, 0xd1, 0xfc, 0xeb, 0xef, 0x42, 0xeb, 0x1e, 0xf1, 0x09, 0x25, 0x7b, 0xc1, 0x68,
	0x44, 0xc6, 0xb4, 0x64, 0x2d, 0x5a, 0x01, 0xd3, 0x73, 0xdb, 0x66, 0xc7, 0xe8, 0x56, 0x6c, 0xd3,
	0x73, 0xf1, 0xa7, 0x06, 0xac, 0xed, 0xb8, 0xae, 0xa6, 0xb9, 0x03, 0xb5, 0xc3, 0x78, 0x86, 0x2b,
	0x2f, 0xdd, 0xba, 0xd1, 0xcf, 0xda, 0xdf, 0xcf, 0x69, 0xf4, 0xa5, 0x28, 0xf5, 0x12, 0x70, 0x33,
	0x05, 0xb7, 0xae, 0x40, 0x6d, 0x2f, 0xfd, 0xfc, 0x38, 0x70, 0x9f, 0x4a, 0x6e, 0x6c, 0x8c, 0x7b,
	0xd2, 0x8e, 0x39, 0x6c, 0xfe, 0xc5, 0x80, 0xd6, 0xc1, 0xc4, 0x75, 0x72, 0x8b, 0xef, 0x41, 0xcd,
	0x89, 0x67, 0x04, 0xf5, 0x9e, 0x4a, 0xbd, 0x48, 0xa9, 0x2f, 0x45, 0xa9, 0x5a, 0xc8, 0x3e, 0x80,
	0x9a, 0x58, 0x87, 0x5a, 0xb0, 0x40, 0x3d, 0x2a, 0x20, 0x1a, 0x76, 0x2c, 0xa0, 0x0e, 0x2c, 0xb9,
	0x24, 0x3a, 0x0c, 0xbd, 0x09, 0x8b, 0x06, 0xa1, 0x9b, 0x9d, 0x4a, 0xac, 0xae, 0xa4, 0x56, 0xa3,
	0x36, 0xd4, 0xa8, 0x33, 0x7c, 0xe0, 0x45, 0xb4, 0x5d, 0xed, 0x54, 0xba, 0x0d, 0x5b, 0x8a, 0xf8,
	0x27, 0x03, 0x5a, 0x7b, 0x21, 0x79, 0x7e, 0x1b, 0x8b, 0x94, 0x72, 0x36, 0x9e, 0xbf, 0x3d, 0x37,
	0x60, 0x6d, 0x9f, 0xd0, 0x39, 0x0e, 0x77, 0x0f, 0x2e, 0xde, 0x27, 0xc4, 0x15, 0x2b, 0xe5, 0x2d,
	0x62, 0x2c, 0x7d, 0x6f, 0xe4, 0xc5, 0x31, 0x59, 0xb1, 0x63, 0x01, 0x5d, 0x82, 0xc5, 0xe0, 0xe8,
	0x28, 0x22, 0x54, 0x44, 0xb5, 0x90, 0xf0, 0x67, 0x06, 0x5c, 0x64, 0xb0, 0xfa, 0x2e, 0xab, 0x50,
	0xa1, 0x8e, 0xc4, 0x63, 0x43, 0xb6, 0x83, 0x33, 0xa5, 0xef, 0x06, 0xa1, 0x30, 0x51, 0x48, 0x68,
	0x03, 0x1a, 0xf2, 0x16, 0xba, 0xc2, 0xc4, 0x74, 0x22, 0x65, 0x53, 0x2d, 0x66, 0xb3, 0xa0, 0xb0,
	0xd9, 0x86, 0x8b, 0x07, 0xe3, 0xa3, 0xc0, 0xf7, 0x83, 0x27, 0x07, 0x11, 0x09, 0x25, 0x19, 0x0b,
	0xea, 0xd3, 0x88, 0x84, 0x63, 0x67, 0x24, 0x7d, 0x9f, 0xc8, 0x78, 0x00, 0x6b, 0xf7, 0x9f, 0x57,
	0x61, 0x9f, 0xd0, 0xd7, 0xc3, 0xe0, 0xc8, 0x4b, 0xfd, 0x5b, 0xa6, 0x70, 0x19, 0xd6, 0xf7, 0x09,
	0xdd, 0x9b, 0x86, 0x21, 0x19, 0xd3, 0x0c, 0x0a, 0xfe, 0xde, 0x80, 0xb5, 0xf8, 0xa2, 0x64, 0xb1,
	0xef, 0x40, 0x95, 0xa9, 0x8a, 0x98, 0xdb, 0x2a, 0xba, 0x57, 0x99, 0xe5, 0x7d, 0x3e, 0xe6, 0x1a,
	0xd6, 0x09, 0x54, 0x99, 0xc4, 0x7c, 0x46, 0x46, 0x8e, 0xe7, 0xcb, 0x38, 0xe3, 0x02, 0x8f, 0xbe,
	0xe0, 0x98, 0xc8, 0x08, 0x8b, 0x05, 0x85, 0x78, 0x45, 0x25, 0xce, 0xce, 0xf0, 0xb1, 0x17, 0x70,
	0xcf, 0x37, 0x6c, 0x36, 0x64, 0x7b, 0x78, 0x23, 0x67, 0x48, 0xb8, 0xdb, 0x1b, 0x76, 0x2c, 0xe0,
	0x6f, 0x0c, 0x68, 0xc4, 0x94, 0x26, 0xfe, 0x53, 0xf4, 0x3f, 0x85, 0xff, 0x86, 0xc6, 0x5f, 0x2e,
	0xfb, 0x3b, 0xf0, 0xfe, 0xd6, 0x80, 0x66, 0x72, 0x8e, 0x8c, 0xfa, 0xcb, 0x50, 0x9b, 0xc4, 0xb2,
	0x60, 0x8f, 0x55, 0xf6, 0xd9, 0xc5, 0x89, 0x20, 0x55, 0xac, 0x63, 0xa8, 0x89, 0xb9, 0xb2, 0x70,
	0x90, 0xec, 0xcc, 0x02, 0x76, 0x95, 0x0c, 0x3b, 0x7e, 0x2f, 0x78, 0x60, 0x7a, 0xe3, 0x21, 0xb7,
	0xa5, 0x6e, 0xa7, 0x13, 0xf8, 0xf3, 0x2a, 0xa0, 0x37, 0xbc, 0xf1, 0xd0, 0x4f, 0x13, 0x10, 0xb3,
	0x60, 0x57, 0xcf, 0x59, 0x5d, 0xd5, 0x82, 0xbc, 0x4a, 0x3e, 0x63, 0xbd, 0x07, 0x8b, 0x3b, 0xf1,
	0xd5, 0x7c, 0xe1, 0x66, 0x58, 0x3f, 0x98, 0x69, 0x7a, 0x2c, 0xfa, 0x21, 0x4d, 0x52, 0xa6, 0x59,
	0x92, 0x32, 0x2b, 0xb3, 0x53, 0x66, 0xb5, 0x38, 0x65, 0x2e, 0x28, 0x29, 0x93, 0x71, 0x3c, 0xe4,
	0xc9, 0xdc, 0xdd, 0xa1, 0xed, 0xc5, 0x38, 0x05, 0x25, 0x13, 0xec, 0xeb, 0x94, 0x5f, 0x3b, 0xf6,
	0xb5, 0x16, 0x7f, 0x4d, 0x26, 0xd4, 0xf4, 0x55, 0x17, 0xf6, 0x25, 0xe9, 0xeb, 0x3a, 0xac, 0x48,
	0x21, 0xda, 0x0b, 0xa6, 0x63, 0xda, 0x6e, 0x74, 0x8c, 0xee, 0xb2, 0xad, 0xcd, 0xa2, 0x57, 0x92,
	0xe4, 0x08, 0x45, 0x95, 0x40, 0xd1, 0xb1, 0xf1, 0xe5, 0x32, 0x8b, 0xe2, 0xef, 0xaa, 0xb0, 0xfe,
	0xda, 0xd4, 0xa7, 0xde, 0x24, 0x59, 0x17, 0xc5, 0x21, 0xf1, 0x2a, 0xd4, 0xc5, 0xc9, 0x46, 0x6d,
	0xa3, 0x53, 0xe9, 0x2e, 0xdd, 0xba, 0xa9, 0x6e, 0x5e, 0xa8, 0xd6, 0x4f, 0xa4, 0x44, 0x1b, 0x6d,
	0xc1, 0xb2, 0x1c, 0xc7, 0xb6, 0x98, 0xdc, 0x16, 0x75, 0xf2, 0x5c, 0xc3, 0xe7, 0x47, 0x13, 0xea,
	0x92, 0xe8, 0x3f, 0x3a, 0x7e, 0x76, 0xb5, 0xf8, 0xe9, 0xcd, 0x75, 0xc4, 0x6a, 0x08, 0xfd, 0x6e,
	0xca, 0x94, 0x92, 0x54, 0x9d, 0x22, 0xa5, 0xa8, 0x55, 0x6a, 0x61, 0x4a, 0xc9, 0xaa, 0xe4, 0xca,
	0xd4, 0x73, 0x8d, 0x89, 0xaf, 0x8c, 0xb4, 0xfe, 0x8d, 0xeb, 0x70, 0x83, 0xbb, 0xcc, 0xf4, 0x5c,
	0xf5, 0xa0, 0xcc, 0xd2, 0x83, 0xaa, 0xe8, 0x07, 0x55, 0x14, 0x12, 0xe9, 0xb5, 0x5d, 0x98, 0x7d,
	0x6d, 0x15, 0xd7, 0x68, 0x3e, 0xff, 0xc3, 0x4c, 0xaf, 0xad, 0x58, 0x97, 0x5e, 0x5b, 0xe1, 0xbd,
	0x33, 0xae, 0xad, 0xa2, 0xd6, 0x4f, 0xa4, 0x44, 0xfb, 0x5c, 0x9d, 0xff, 0xb5, 0x01, 0x75, 0x49,
	0xe1, 0x85, 0x7b, 0x7f, 0x57, 0xf3, 0x7e, 0x6f, 0x1e, 0x07, 0x69, 0x07, 0x80, 0xa1, 0xf9, 0x30,
	0xbe, 0xc5, 0xb1, 0xdb, 0x11, 0x54, 0xa9, 0x33, 0x8c, 0x5d, 0xde, 0xb0, 0xf9, 0x18, 0x9f, 0x42,
	0xf3, 0x41, 0x30, 0xf4, 0xc6, 0xb2, 0x42, 0xbb, 0xad, 0x54, 0x38, 0x9b, 0x2a, 0x6a, 0x76, 0x65,
	0xb6, 0xc8, 0xb9, 0x53, 0x5a, 0xe4, 0x58, 0x50, 0x9f, 0x38, 0x51, 0xf4, 0x24, 0x08, 0x5d, 0xe1,
	0x99, 0x44, 0xc6, 0x5f, 0x1a, 0x70, 0xc1, 0x26, 0x43, 0x2f, 0xa2, 0x69, 0x91, 0xf8, 0x7f, 0x85,
	0x82, 0x56, 0xa6, 0x68, 0x8b, 0xb3, 0x2c, 0x1e, 0x0a, 0x16, 0x65, 0x91, 0x90, 0x30, 0x34, 0x67,
	0x31, 0xac, 0xa8, 0x0c, 0x6f, 0xfd, 0xb6, 0x0a, 0x0d, 0x9b, 0x38, 0xfe, 0x5b, 0x8c, 0x01, 0x7a,
	0x04, 0x0b, 0xdc, 0x09, 0xc8, 0x9a, 0xed, 0x19, 0xeb, 0xf2, 0x8c, 0xba, 0x10, 0xff, 0xfb, 0xa3,
	0x9f, 0x7f, 0xfd, 0xc2, 0x5c, 0xc7, 0xab, 0xfc, 0xd9, 0xcf, 0x48, 0x45, 0x03, 0x9f, 0x69, 0xde,
	0x35, 0x7a, 0xe8, 0x11, 0xd4, 0xa5, 0x71, 0xe8, 0x4a, 0xa9, 0xd1, 0xb3, 0x01, 0xd6, 0x39, 0xc0,
	0x05, 0x0c, 0x29, 0x00, 0xdb, 0xda, 0xe1, 0xed, 0x84, 0x4c, 0x95, 0x8e, 0xae, 0xa9, 0x3b, 0x14,
	0xd6, 0xf0, 0xb3, 0x61, 0xd6, 0x38, 0xcc, 0x12, 0x6a, 0x24, 0x30, 0xe8, 0x1d, 0x80, 0xb4, 0x7e,
	0x47, 0x9b, 0x67, 0x54, 0xf6, 0xb3, 0xb7, 0x6e, 0xf1, 0xad, 0x57, 0xac, 0x74, 0x6b, 0x66, 0xc0,
	0x31, 0x40, 0xfa, 0x2e, 0xd1, 0x77, 0xcf, 0xbd, 0x58, 0x2c, 0x6b, 0x76, 0x69, 0x8b, 0x3b, 0x1c,
	0xc0, 0x42, 0x6d, 0x0e, 0x20, 0xea, 0xdb, 0x68, 0xf0, 0x4c, 0x86, 0xc8, 0x29, 0x9a, 0x02, 0xa4,
	0xaf, 0x26, 0x1d, 0x2c, 0xf7, 0x9e, 0x2a, 0x05, 0xeb, 0x71, 0xb0, 0x2d, 0xbc, 0x39, 0x0b, 0x6c,
	0x10, 0xa7, 0x17, 0x66, 0xe3, 0x09, 0x34, 0xb3, 0xef, 0x3b, 0x74, 0x55, 0x73, 0x51, 0xfe, 0xed,
	0x57, 0x0a, 0x7d, 0x83, 0x43, 0x5f, 0xed, 0x9d, 0x05, 0x8d, 0x46, 0xd0, 0xcc, 0x3e, 0x72, 0x75,
	0xdc, 0x82, 0x07, 0xb0, 0x75, 0x6d, 0x8e, 0x5f, 0x60, 0x19, 0x8b, 0x68, 0x39, 0xee, 0x71, 0xc9,
	0xed, 0x43, 0x68, 0x66, 0x5f, 0xe6, 0x3a, 0x5c, 0xc1, 0xab, 0x7d, 0x3e, 0x38, 0x8b, 0xc3, 0xb5,
	0x10, 0x52, 0xe0, 0x06, 0x47, 0x84, 0xb8, 0x68, 0xc4, 0xc3, 0x47, 0xd6, 0xe2, 0xf9, 0xf0, 0x51,
	0x1b, 0x0a, 0x56, 0xe7, 0xac, 0x02, 0x15, 0x6f, 0x70, 0xb0, 0x4b, 0xa8, 0xa5, 0x82, 0x3d, 0x63,
	0x75, 0xd9, 0x29, 0x0a, 0x60, 0x59, 0xe9, 0x9f, 0x20, 0x7c, 0x76, 0x73, 0x65, 0x0e, 0xd0, 0x36,
	0x07, 0x45, 0x58, 0x75, 0x68, 0x1c, 0x3a, 0xcb, 0x4a, 0x53, 0x4a, 0x07, 0x2c, 0xea, 0x58, 0xcd,
	0x01, 0xb8, 0xc9, 0x01, 0xff, 0x65, 0x15, 0x5a, 0xc9, 0x70, 0x23, 0x58, 0x56, 0xda, 0x6d, 0x3a,
	0x6e, 0x51, 0x2f, 0x6e, 0x7e, 0xef, 0xf6, 0x8a, 0xbd, 0xfb, 0x14, 0x20, 0x6d, 0x1e, 0xea, 0x87,
	0x99, 0x6b, 0x2b, 0x16, 0xc3, 0x65, 0xcb, 0x16, 0xdc, 0xe5, 0x70, 0x18, 0x5f, 0x29, 0x82, 0x1b,
	0xc8, 0x52, 0x83, 0xd9, 0xfb, 0x01, 0x2c, 0xb1, 0x4c, 0x29, 0x6b, 0x80, 0x33, 0xb1, 0xaf, 0xcd,
	0xf1, 0xa3, 0x8d, 0xff, 0xc3, 0xe1, 0x37, 0x51, 0x39, 0x3c, 0xfa, 0xd0, 0x90, 0xce, 0x96, 0xa6,
	0x17, 0x3a, 0xfb, 0xb9, 0xad, 0x17, 0x29, 0xaa, 0x87, 0x4b, 0xe1, 0x07, 0xcf, 0x3c, 0xf7, 0x14,
	0x7d, 0x6c, 0xc0, 0x05, 0xad, 0x0b, 0x8d, 0xb4, 0x26, 0x4e, 0x71, 0x93, 0x7a, 0x8e, 0x43, 0x2f,
	0x3f, 0x05, 0xf9, 0x24, 0x60, 0xa7, 0xf0, 0x89, 0x01, 0x6b, 0xb9, 0xee, 0x36, 0xba, 0x9e, 0x4b,
	0x97, 0x7f, 0x95, 0x89, 0x38, 0x90, 0x5e, 0x39, 0x13, 0xf4, 0x26, 0xd4, 0x44, 0x8f, 0x1e, 0x6d,
	0xe4, 0x32, 0x4a, 0xa6, 0x75, 0xaf, 0x67, 0xe9, 0x6c, 0x49, 0xa6, 0xfd, 0x92, 0xb2, 0x8a, 0x6c,
	0xf7, 0xfa, 0xdb, 0x5b, 0xc7, 0xa1, 0x43, 0x83, 0xe8, 0xbf, 0xe9, 0xdf, 0x09, 0xfa, 0x9f, 0x0b,
	0x2f, 0x9d, 0x6c, 0x3f, 0x5e, 0xe4, 0x7f, 0x15, 0xdc, 0xfe, 0x33, 0x00, 0x00, 0xff, 0xff, 0xd0,
	0x90, 0x39, 0xe6, 0x7a, 0x18, 0x00, 0x00,
}
